### ISSUE TITLE
New AAPS-Omnipod "ACTION" tab does not allow resetting "Insuline age" and "Canula age"

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#107]
AndroidAPS 2.7-omnipod-0.3-SNAPSHOT
Build EROS_0.2-341-g8c803f7e0

**Configuration:**
* Local AAPS profile

**Problem:**
New ACTION tab does not allow resetting "Insuline age" and "Canula age", only "Pump Battery Change". As a result AAPS main view (with option "Show status lights" enabled) shows wrong values.
See screenshot.

Additional remark:
I know the CAN/INS/BAT do not really aplye for OmniPod but for me the status lights do/could show valuable information on Sensor age, and Pod/Canula Age and Resevoir content.
So I do not want to disable the AAPS main view status line .
(AFAIK I can not disable showing "Insuline/Canula" values?)

*Expected behavior, either:*
- Must have:
Show additional buttons like "Insuline age" and "Canula age" for resetting
- Should have:
Insuline- and Canula- age are automatically reset, f.i. on resetting "Insuline age".

*Feature request:*
* Auto reset values for Insuline, Canula and Battery on Pod init.

![Screenshot_20200315-100217_AndroidAPS](https://user-images.githubusercontent.com/45144129/76701362-be426e00-66c0-11ea-9b00-76f086a2ba26.jpg)

**Comment by andyrozman** [comment]
Reopen this is Core product

**Comment by teleriddler** [comment]
In AAPS core there is a the **Site Change** moved from the **Care Portal** to the **Actions tab** and is now under **Prime/Fill**.   

I have installed the latest version of AAPS 2.6 and can verify that this functionality exists there, however in AAPS-Omni, the icon has been removed, understandably as Omnipod really executes the Prime/Fill automatically in pod initialization.

https://androidaps.readthedocs.io/en/latest/CROWDIN/pt/Usage/CPbefore26.html

![image](https://user-images.githubusercontent.com/7156327/76744128-10909700-6774-11ea-9835-5abd3813f4bd.png)

**Suggestion**

Would it be possible to enable the **Prime/Fill** button but just update the button text to **Change Site**?  If not, then we need a way to mark a site change so the Canula Age can be correctly reset and reflect site changes in NS.

**OR**

**Automatically reset the Canula Age** upon successful completion of insertion of a new site, then the button could remain hidden and the process is automated.

Insulin Age I personally use for when I open a new bottle of insulin so I don't use it measure the age of the insulin in the Pod because it is only in there for 3 days until the next change.  I find keeping track of the bottle age to be a more useful use of this feature.

**Comment by andyrozman** [comment]
I will reset cannula age in code after Init is successful.

**Comment by vanelsberg** [comment]
> I will reset cannula age in code after Init is successful.

That would fix for me!

Resetting "Insuline age" on Pod init seems also logical for AAPS-Omnipod?
Currently I see no way to do this with the current build.

**Comment by vanelsberg** [comment]
@andyrozman 
Thinking again on this I realize that resetting the _cannula age in code after Init is successful (milestone 6)_ is only solving part of the problem. As the screen print shows also "Insulin age" can not be reset through the action tab. Currently I am using "Pump battery change" to register Pod age but somehow this does not feel logical.
For OmniPod one would think there is no need to bother the user with manual interaction at all. 

_I would suggest also resetting "Insulin age" and "Pump battery change" on Pod init._
Also, as the "Pump Battery Change" button is then no longer needed it could be made invisible?

**Comment by bartsopers** [comment]
@andyrozman could you look into @vanelsberg's suggestions?

**Comment by vanelsberg** [comment]
@andyrozman @bartsopers I think this was solved with 0.4 dev.

**Comment by bartsopers** [comment]
@vanelsberg Are you sure this is also fixed for isulin age and pump battery change?

**Comment by vanelsberg** [comment]
AFAIK, yes.
Insulin age used to show cumulative time since last install.
From what I see on recent 0.4 dev commits, on the ACT tab "Insulin age" shows as "-".
Also on Nightscout, IAGE has no value.

![Screenshot_20200819-091740](https://user-images.githubusercontent.com/45144129/90604403-13008c80-e1fd-11ea-880f-01d5e6767ee4.png)

**Comment by vanelsberg** [comment]
Also, Canula age where perfectly reset on Pod change.

Pump battery rest needs manually issuing a "Pump Battery Change"  on the activity tab after Pod change.
Maybe this could also be automaticcally reset through Pod init?

Not yet tested on current dev 0.4 1 dev commit.
**Will retest and let you know for my next Pod change!**

**Comment by bartsopers** [comment]
@andyrozman could you please look at removing the "Pump Battery Change" button on the activity tab and resetting it automatically after activating a new pod instead?

**Comment by vanelsberg** [comment]
> @andyrozman could you please look at removing the "Pump Battery Change" button on the activity tab and resetting it automatically after activating a new pod instead?

If that is feasable that would be awesome!

**Comment by vanelsberg** [comment]
Retested for dev/1.4.1:
- Insulin age shows "-" and is not updated
- Canula age is automatically reset on Pod init
- Pump battery is not autoreset, but can be manually reset through the "Pump Battery Change" button.

**Comment by bartsopers** [comment]
Fixed:
- Reset Pump Battery and Insulin age after activating a new Pod
- Hide Pump Battery Change button in the Actions tab for Omnipod
