### ISSUE TITLE
restarting AAPS with active pod gives erroneous message "no active pod"

### ISSUE THREAD

**Issue by ZandMarc** [AAPS-Omnipod/AndroidAPS-OLD#54]
With a pod active, I force stopped AAPS en started it again to reconnect RL. But then I got the message "no active pod". Erroneous: when I hit refresh in Omnipod tab the pod showed up.

**Comment by andyrozman** [comment]
Please if this happens again, I need logs... Without logs and snapshots of the state, there is not much I can do...

**Comment by bartsopers** [comment]
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4112036/AndroidAPS.log)
This log is for both this issue and #15. Please note that because of #15 (and possibly also this issue), there is no closed loop as AAPS thinks the pump is suspended.
The log starts after rebooting AAPS. After RL is initialized, I get the pump suspended notification. Please refer to below screenshot for the time.
![Screenshot_20200125-074504](https://user-images.githubusercontent.com/15631208/73121524-1390b780-3f7b-11ea-905f-b2c747c77e14.png)

I went to sleep again after this, and when I woke up, the pump suspended notification was still there, and there also was a No pod active notification now. That notification appeared somewhere between the first and the last screenshot. The log covers all time between both screenshots.
![Screenshot_20200125-103155](https://user-images.githubusercontent.com/15631208/73121529-34f1a380-3f7b-11ea-85dc-f8c5bf233203.png)

**Comment by ZandMarc** [comment]
This is the log of the moment I opened this issue for. At 11.23-11.24 there is a notification "no active pod" in the logs. After that there's a "refresh" (done by me) and the active pod is picked up again.
[AndroidAPS._no_active_pod_false.txt](https://github.com/AAPS-Omnipod/AndroidAPS/files/4112043/AndroidAPS._no_active_pod_false.txt)

**Comment by andyrozman** [comment]
This might be fixed already with fixes on #15

**Comment by bartsopers** [comment]
This has probably been fixed. Please re-report if the problem still exists after the 0.4 release.
