### ISSUE TITLE
Priming a pod sometimes fails

### ISSUE THREAD

**Issue by bartsopers** [AAPS-Omnipod/AndroidAPS-OLD#60]
Although pairing & pairing works for most people, several users have reported failures in priming. It seems that assigning an address always succeeds, but priming doesn't. It seems to fail with a communication timeout.

We should investigate the cause of this issue. Loop and Omnicore user do not experience similar issues, so I suspect that there is a problem in our code somewhere.

**Comment by oakeley** [comment]
[AndroidAPS._2020-01-19_11-10-12_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4082796/AndroidAPS._2020-01-19_11-10-12_.0.zip)

Will contain some Omnicore logs too

**Comment by Davud2020** [comment]
I had the same issue.
Modified RileyLink 916MHz to BLE Bridge Complete Kit (RILEYLINK916)  October 2018

[AndroidAPS_old.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4082884/AndroidAPS_old.log)

**Comment by Marije22** [comment]
First time pairing and priming a pod did not succeed for me. Tried several ways to make it work. Changing the pod seemed to be the only solution.  

[wetransfer-d45140.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4083097/wetransfer-d45140.zip)

**Comment by vanelsberg** [comment]
Looks like issue #79 ??

**Comment by Davud2020** [comment]
That issue appeared again.
[AndroidAPS_2020-02-01_23-43-34.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4144280/AndroidAPS_2020-02-01_23-43-34.zip)

**Comment by bartsopers** [comment]
[AndroidAPS_LOG_1580506295669.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4239037/AndroidAPS_LOG_1580506295669.log.zip)

**Comment by avivaac** [comment]
Wasn't able to deactivate, or pair and prime a new pod this evening.  Tried everything, swapped RL and 2nd pod attempt and it eventually worked.  Ive attached logs and screenshots.  
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4277470/AndroidAPS.log)
[AndroidAPS._2020-03-02_18-18-05_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4277471/AndroidAPS._2020-03-02_18-18-05_.0.zip)

**Comment by avivaac** [comment]
![IMG-20200302-WA0000](https://user-images.githubusercontent.com/52380331/75709966-9ebc4600-5cbb-11ea-9c5b-7ed2934d5578.jpg)
![IMG-20200302-WA0001](https://user-images.githubusercontent.com/52380331/75710001-a67bea80-5cbb-11ea-87c2-b20f46e2b635.jpg)
![IMG-20200302-WA0002](https://user-images.githubusercontent.com/52380331/75710021-b09de900-5cbb-11ea-8f1a-cbc1cd856772.jpg)
![IMG-20200302-WA0003](https://user-images.githubusercontent.com/52380331/75710036-b5fb3380-5cbb-11ea-851a-8b6ba48707ca.jpg)
![IMG-20200302-WA0003](https://user-images.githubusercontent.com/52380331/75710049-bd224180-5cbb-11ea-96e3-9cb4a5d0d843.jpg)
![IMG-20200302-WA0004](https://user-images.githubusercontent.com/52380331/75710081-c8756d00-5cbb-11ea-9a17-bdef1367e98a.jpg)
![IMG-20200302-WA0005](https://user-images.githubusercontent.com/52380331/75710090-cdd2b780-5cbb-11ea-9d4e-1aa6e878fecb.jpg)

**Comment by nhobbs7** [comment]
I had a communication issue over the final hours of the pod (starting after it expired at 72 hours so I could not successfully communicate with the pod in the extra 8 hours). Attempted standard troubleshooting (force close app, toggle bluetooth, restart phone, restart rileylink, leave phone and rileylink off for 1 min, charge rileylink). I could not deactivate the first pod so I selected "Reset Pod". When I initialized a new pod, the priming occurred successful and the canula insertion occurred properly, but there was a communication error and the app could not verify the insertion. The option to retry repeatedly failed to meet success on the insert canula screen and after leaving that window, when "Refresh" was selected on the Omnipod tab, the pod history message indicated "the pod is in a wrong state".  After several hours, when returning to the init pod option, it successfully connected.

AndroidAPS 2.6-Omnipod-0.2
Running on Moto X4 (US-Google Fi version). Android version 9.
-Standard Rileylink + wireless charging kit from LoopCases. Has been functional for 5+ pods since soldering for wireless charging. Unlikely to be related to issue.
-Traveled by Airplane (2 hour timezone shift) morning before issue occurred and did not verify the time updated correctly before sleeping multiple hours. Likely unrelated, but I can find the older logs if it may be useful.
-This may also fit under the "Communication Failed" issue as the cause may not relate to the priming itself.


![Screenshot_20200310-130622](https://user-images.githubusercontent.com/60197130/76346465-10574e00-62d3-11ea-8431-8e6dae5e0894.png)
![Screenshot_20200309-194957](https://user-images.githubusercontent.com/60197130/76343558-47773080-62ce-11ea-9963-ccd3c418bbbf.png)
![Screenshot_20200309-200447](https://user-images.githubusercontent.com/60197130/76343569-4c3be480-62ce-11ea-98e6-72f46a3026ea.png)


[AndroidAPS_LOG_1583802929320.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4313946/AndroidAPS_LOG_1583802929320.log.zip)

**Comment by bionictom** [comment]
Adding my log from the problem with priming.
It worked after restarting phone and RL

![2020-03-18 22 58 00](https://user-images.githubusercontent.com/28786121/77011419-21a3f880-696c-11ea-883a-c9bcef513d9e.png)

[AndroidAPS_LOG_1584568640610.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4351543/AndroidAPS_LOG_1584568640610.log.zip)

**Comment by D-Cudz** [comment]
[AndroidAPS._2020-04-18_23-17-24_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4499763/AndroidAPS._2020-04-18_23-17-24_.0.zip)

Everything has been going well after trying this system for the past 2 weeks until now. I had a screamer when trying to pair the pod so threw that out, reset my phone and tried a new pod and then I got the error message seen in the attached log at about 10:50pm. AAPS said that I have to deactivate it and try a new one so I deactivated it on the app. Says it worked but then I checked to see if I could pair it with the Omnipod PDM and it paired fine so it couldn't have been deactivated. Strange. Thanks.

**Comment by Davud2020** [comment]
Priming failure unsuccessful
the fault occurred between 17:17 - 17:40
[AndroidAPS._2020-06-02_17-44-24_.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4718968/AndroidAPS._2020-06-02_17-44-24_.zip)
![20200602_182943](https://user-images.githubusercontent.com/48062504/83555936-59ecb900-a50f-11ea-8475-dd11ea1c44df.jpg)
![20200602_182957](https://user-images.githubusercontent.com/48062504/83555939-5a854f80-a50f-11ea-9b3c-eaf6d65d2212.jpg)

**Comment by Davud2020** [comment]
new priming issue
the fault occurred at 19:41
[AndroidAPS.log](https://github.com/AAPS-Omnipod/AndroidAPS/files/4754217/AndroidAPS.log)
[AndroidAPS._2020-06-09_16-24-07_.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4754242/AndroidAPS._2020-06-09_16-24-07_.zip)

**Comment by bartsopers** [comment]
In 0.4 we did a lot of improvements in the Pod activation process. Closing this issue for now, please re-report if problems still exist after the 0.4 release
