### ISSUE TITLE
Pump suspended - can not resume?

### ISSUE THREAD

**Issue by vanelsberg** [AAPS-Omnipod/AndroidAPS-OLD#91]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

Configuration:
- Local AAPS profile

Problem:
AAPS alerted on a profile change back to 100% (beep, mute, OK)
- AAPS suspended Pump.
- Pod status shows some _uncertain failure_s on "Get Pod Status".
- Pod seems alive and is not beeping/screaming.

_Unable to resume pump from suspension._
Tried AAP exit -> for-kill through settings -> restart

Possible causes:
Unknown.
See logs at approx 15:55:
[AndroidAPS_LOG_1581722265917.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4208696/AndroidAPS_LOG_1581722265917.log.zip)

**UPDATE:**
One hour later I retried fixing:
Finally managed to "unsuspend" the pump AAPS seems fine. Not sure about the steps that resulted in unsuspending: as far as I remember (se log attached below):

First I was wondering if maybe my (local) profile was data was not accepted by the pump?
So I double-checked and **resaved the profile**. Then switched profile to 120% hoping it would force resending a TBR command _**(*)** I think this was at step 5 below?_

1. Restarted AAP, pump showed suspended
2. Disable loop
3. Disconnect the pump
4. Reconnect the pump
5. Set profile to 120% **(*)**
6. (Tapping now showed the option): unsuspend pump)
7. Enable loop

From here AAPS and  pump where fine (see logs at aprox 16:53:22)
[AndroidAPS_LOG_1581782210634.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4208738/AndroidAPS_LOG_1581782210634.log.zip)

**Comment by dar-kod** [comment]
AndroidAPS 2.6-omnipod-0.2
Build EROS_0.2 (release)

Problem: **Pump suspended** could not be fixed with working temporary fix:

1. Use the refresh button in the Omnipod tab
2. Do a profile switch

I tried also other recommended steps: 

1. Restarting AndroidAPS with Force Stop in the Settings -> Apps
2. Bluetooth off/on
3. RileyLink off/on

After those steps the RileyLink is connected but very short time like a few minutes and the pump is suspended. RileyLink battery is fully charged.

I also tried to switch to virtual pump and back to Omnipod but without result.

See the logs at time before 20:56 when I decided to change a pod. It happened probably between 19:17 and 20:48. Some timing are listed:

- At 19:17 I saw first time **Pump suspended** and I decided to give a small bolus 0.05.
- At 19:52 profile switch.
- At 19:55 profile switch.
- At 20:00 profile switch.
- At 20:40 profile switch.
- At 20:42 profile switch.

[AndroidAPS._2020-02-15_20-40-10_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4209076/AndroidAPS._2020-02-15_20-40-10_.0.zip)

**Comment by vanelsberg** [comment]
@bartsopers @andyrozman Possibly not be related, just trying to create context:

**Additional remarks:**

_AAPS has been running remarkably stable!_:
Have been running EROS from version 1.1 dated 27 jan.
No operational communication or connection problems other then what is expected (out of range).
Seamlessly activated 7 Pods, 1 screamer (as far as I can judge the problem was in the Pod itself)

_I am using an AAPS local profile_:
The initial view on the profile is always correct. But very often when opening the view for a 2nd time  profile scheduled times are shifted by 2 hours backwards (wrong timezone?) . A standard close/reopen AAPS solves this. Never saw this as much of a problem.
I have seen this behavior consistently since AAPS version 2.3

So general bug in AAPS, not related to the OmniPod driver. Still, thought it might be worth mentioning? Considering the fact that I suspected inconsistencies in message send to the Pod when switching profile that resulted in pump suspension as reported. Some sort of profile corruption that caused my problem maybe?

**Comment by Davud2020** [comment]
I had this issue. If you have this issue you can't loop and give boluses.
so I need to change a new pod.
[AndroidAPS.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4230038/AndroidAPS.zip)

**Comment by danielhers** [comment]
Just had this issue after a Pump Unreachable. 
Killed the app and bolused successfully but then it got suspended again. 
Profile switch to 101% for 10m fixed it.

**Comment by Kaivish** [comment]
Anyone tried to just tap on refresh in pod tab? Had a pump suspended issue, consequently loop stopped as pod was not contacted for more that 4 hrs. But i just went to pod tab and tapped refresh and pump came out of suspended state.
This suspended pump came up just after aaps restarted itself. Seeing aaps start logging on ns and shortly after occured the pump suspended issue. Maybe just a coincidence.

**Comment by danielhers** [comment]
Yes, that's actually the first thing I tried, but it didn't help.

**Comment by Kaivish** [comment]
Uploading logs for pump suspended issue. Timeline is 00.01.xx

Note that i was abke to go back to normal closed loop after only refreshing status in pod tab. 



[AndroidAPS_LOG_1582515940110.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4244162/AndroidAPS_LOG_1582515940110.log.zip)

**Comment by danielhers** [comment]
Here are my logs. Pump unreachable at 00:08. Bolus at 03:08 and then profile switch.
[AndroidAPS._2020-02-24_03-05-46_.0.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4244198/AndroidAPS._2020-02-24_03-05-46_.0.zip)

**Comment by teleriddler** [comment]
I had the exact same problem today after weeks of stable 0.2 running.  

AndroidAPS 2.6-Omnipod-0.2
Build: EROS_0.2-2020.01.28-10:10
NS Version: 13.0.1
Engineering Mode - enabled

I recently switched to using a Local Profile (2 weeks ago) in anticipation of the new features with the upcoming 2.6 merge.  Nothing special was done to trigger the phenomenon, I simply got a warning that my pump was unreachable.  Normally I carry the RL in my jean pocket.   The only difference today as that I have a sweater with a pocket on the left arm that exactly fits the RL and I had it in there today because I had an optical surgical procedure (no MRI, etc, just a shot in a chair so should not affect the RL).  Note, I have also used this sweater pocket from time to time before without issue.

For those of you trying to rescue an active POD, no need to take the route I did below but rather skip directly to #9 setting a Profile Switch to another percentage (higher or lower based on your current BS situation).

**Things I tried:**
_Note: after each step below I also did the following
   a) used the "Refresh" button on the Omnipod menu
   b) used the "Pulse Log" button on the Omnipod menu
   c) From "RL Stats" menu clicked blue refresh circular arrow_

1) Kill AAPS and restart 
    RESULT: Did not resolve "Pump Suspended"

2) Turn Bluetooth on and off 
    RESULT: Did not resolve "Pump Suspended"

3) Power cycle RL 
    RESULT: Did not resolve "Pump Suspended"

4) Soft boot phone
    RESULT: Did not resolve "Pump Suspended"

5) Changed pump driver in Configuration to Virtual Pump and then changed back to Omnipod - 
After execution RL has a working connection again but does not recognize the POD, I had to resolve that issue first.  The whole time "Pump Suspended" status was always shown.

    RESULT: Did not resolve "Pump Suspended"

6) Reset RL Config - resolved the missing POD connection issue

    RESULT: Did not resolve "Pump Suspended"

7) Set temporary basal rate to hypo (target 80) and then canceled the TBR before and after cancelling I was not able to unsuspend the pump.

    RESULT: Did not resolve "Pump Suspended"

8) Searched open issues and found this one.   Tried change one basal rate in local profile, saving and activating the profile.

    RESULT: Did not resolve "Pump Suspended"

**9) Profile Switch to 120% set, then deactivated.**

    RESULT: Resolved "Pump Suspended"

Attaching logs but for those of you trying to rescue an active POD, no need to take the route I did above but rather skip directly to setting a Profile Switch to another percentage (higher or lower based on your current BS situation).

The main concern with this issue, as others have stated, is that you are not able to deliver a bolus, set a TBR, use SMB, etc.  Basically you can't dynamically dose Insulin and the Pod falls back to its programmed basal rates.

  -TR
[AndroidAPS_LOG_1584018869671.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4324444/AndroidAPS_LOG_1584018869671.log.zip)
[AndroidAPS_LOG_1584018870076.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4324445/AndroidAPS_LOG_1584018870076.log.zip)
[AndroidAPS_LOG_1584018877992.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4324446/AndroidAPS_LOG_1584018877992.log.zip)

**Comment by andyrozman** [comment]
@vanelsberg I have seen this behavior consistently since AAPS version 2.3... Could you please report this to AAPS core please... (and check if similar issue was already opened)

**Comment by elgu11** [comment]
I still have the same problem with Eros_03. @andyrozman 
[AndroidAPS_LOG_1584884289173.log.zip](https://github.com/AAPS-Omnipod/AndroidAPS/files/4397952/AndroidAPS_LOG_1584884289173.log.zip)
Lost contact: 
11:31:02.499 [RxCachedThreadScheduler-54] D/APS: [LoopPlugin.applyTBRRequest():513]: applyAPSRequest: Pump inte initierad

**Comment by vanelsberg** [comment]
> @vanelsberg I have seen this behavior consistently since AAPS version 2.3... Could you please report this to AAPS core please... (and check if similar issue was already opened)

Will do!
Just think this might also be related to driver logic in combination with comm errors during profile switch operations?

Observation:
Problem is always the result of a profile switch failure and can be solved by manually switching profile.

I would say switching profile suspends the pump. Then when comm errors occur on setting the new profile, the action is aborted and the pump is not resumable due to an "unknow" profile state?
Maybe, driver does/can not handle this state and/or AAPS does not get informed there is a problem?

**Comment by elgu11** [comment]
@vanelsberg 
Of course, now I understand why I have started to get these errors that I did not previously with eros-01. From eros-02 I started with "Automation" and created a profile switch at high glucose (> 9 mmol).

**Comment by mick711** [comment]
Hi i have this issu today and send by email log, when it come sometime like this log when time and time zone issue come that solve the problem .

**Comment by mistermintsgh** [comment]
I've just had this problem twice today.

Steps to recreate my instance:
1. Set profile change for set period (in my case I switched from profile A to profile B for 60 minutes)
2. At end of the predetermined profile switch duration alarms sound to say that there was a communication error and profile could not be switched back
3. Pump suspended message displayed on screen (see screen shot)
![Screenshot_20200418-070639_AndroidAPS](https://user-images.githubusercontent.com/42671801/79630860-cc1a6180-814c-11ea-8369-81e98d01445b.jpg)


During this time my pump was still connected - I could refresh the status on the pod tab, could still bolus, and default basal was being delivered

Only way I could unsuspend the pump was to force a profile switch to another profile, then back to the one I wanted to be using.

**Comment by avicorp** [comment]
Fix request: If the system is in a state of pump suspended due to a failing profile switch, massage will show "Suspended pump dou to comonication fail on profile switch. Check rileylink connectivity or try to reset the profile." Two buttons: "Ok" and "Reset profile".

**Comment by bartsopers** [comment]
The false pump suspended notifications are fixed in 0.4
